<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Build.props" />
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Foreseerr.Jellyfin/Foreseerr.Jellyfin.csproj" />
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
